# Generated by Django 4.2 on 2024-10-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile/avatar.png', upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Default username', max_length=50, unique=True),
        ),
    ]
