# Generated by Django 4.2 on 2024-10-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_profile_image_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Default username', max_length=50),
        ),
    ]
