# Generated by Django 4.2 on 2024-10-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
